# Make it possible to switch adapters by passing the ACTION_CABLE_ADAPTER env variable.
# For example, you can use it fallback to the standard Action Cable in staging/review
# environments (by setting `ACTION_CABLE_ADAPTER=redis`).
development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://localhost:6379/12

ru_production:
  adapter: redis
  url: redis://localhost:6379/12
